### ISSUE TITLE
Remember the selected UV for Fast Normals

### ISSUE THREAD

**Issue by Art4DD** [Mustard2/MustardSimplify#1]
Hi, is it really possible to force the addon (Mustard Simplify) to remember the UV that is selected in the normal map node?

I use materials that use several UV in one at once, after clicking on the "Fast Normals" button, the selected UV disappears from the node because of this, the material begins to use one UV, which was selected by default.
![image-2](https://github.com/Mustard2/MustardSimplify/assets/55113758/608e9576-6d33-40a6-a50c-2c41bc90f63e)
![image-3](https://github.com/Mustard2/MustardSimplify/assets/55113758/c100622b-9ee7-4842-b9f6-0f94c7802420)

**Comment by Mustard2** [comment]
Hi! Thank you for reporting this.

It is a bug, and atm there is no way for the add-on to force this. I will update the add-on to implement this.

**Comment by Mustard2** [comment]
Solved in #3 . If you want to try, let me know if it works!
