### ISSUE TITLE
Scene not being unsimplified. 

### ISSUE THREAD

**Issue by NuclearWaffle0** [Mustard2/MustardSimplify#16]
Not sure what exactly caused this, but I think it's when I updated to the latest version and because I left the scene simplified when I updated. But now practically the entire scene is unaffected by the code even if I revert back to older versions. This persists through save files and even if I append the objects to different scenes. I messed around with it to see if I could fix it myself, and found out that if I manually enable / disable what the code is suppose to affect, then that 1 thing will be affected again. So I am guessing it's possibly a memory leak.

Also just found out, if you disable something the code is suppose to affect before you simplify the scene, you'll reproduce the same effect.
 
I.E. Disable Auto smooth > Simplify Scene > Unsimplify. The thing you disabled autosmooth on will no longer be affected by the code anymore. Guessing this is what happened for me, just on a larger scale lol. Still not sure how I did that though. 

https://github.com/Mustard2/MustardSimplify/assets/72324226/8b63e245-56e8-40e1-8840-c2af21c1e166

https://github.com/Mustard2/MustardSimplify/assets/72324226/64fe3237-8e9f-482d-93e2-5db6fa50c744

**Comment by Mustard2** [comment]
Thanks for reporting this! It surely seems like a bug.

Do you have the affected scene to share? Even without textures, so it's lighter. :)

**Comment by Mustard2** [comment]
One thing here: the addon works in such a way that it tries to revert to the status it finds before hitting the Simplify button. There was a bug in some early version that was preventing this to work properly when you closed the file and reopened it, and then Unsimplify. After updating it might be that the new version kicked in and the old data were overwritten.

But if you send me the scene I can check :)

**Comment by NuclearWaffle0** [comment]
That does make sense. I Usually disable and revert all of my addons back to the default settings before updating to prevent stuff like this. But for whatever decided not to this time T_T. But no probs though. Don't remember the last site you linked, so uploaded it to mega. If you'd like a link from your preferred website just lmk ^^

https://mega.nz/file/4iclAaqJ#8PYxLj3F9knhPjp0veFIOhm6ZarF2Ar5LMSoKtQdYx8

**Comment by Mustard2** [comment]
Thanks for the link!
I downloaded the file and removed the link just in case. :)

**Comment by NuclearWaffle0** [comment]
Np. If you need anything else from me, just lmk. Have fun coding my dude ^.^/

**Comment by Mustard2** [comment]
Closing this because as far as I've seen from the scene it was an error of compatibility between versions.
But please feel free to reopen this if you still have similar issues!
