### ISSUE TITLE
The addon should disable shape keys that are controlled by drivers, if the checkboxes on drivers and shape keys are activated.

### ISSUE THREAD

**Issue by Art4DD** [Mustard2/MustardSimplify#2]
Addon does not very thoughtfully disable the drivers. In diffeomorphic, all shape keys that are controlled by drivers are disabled along with the drivers. Your driver is disabled, but shape keys remain enabled if their values are greater than 0.

You need to make it so that if the shape key is controlled by the driver, then it should also be disabled because the enabled shapekey consumes fps.

With diffeomorphic "Disable Drivers" I get 54 fps
With your addon with drivers and shape keys checked, I get 42fps. Because shape keys controlled by drivers remain enabled (those with a value greater than 0).

**Comment by Mustard2** [comment]
Hi! Thank you for the suggestion!

The add-on was never intended to work specifically for Diffeomorphic, but I agree that a better support would be a nice additional feature.

For the problem itself, I was indeed planning to deal with the driver simplication. In particular, I will add the possibility to choose which drivers to disable (e.g., if they are = 0, if they are driven by drivers, etc..).

**Comment by Art4DD** [comment]
> I will add the possibility to choose which drivers to disable (e.g., if they are = 0, if they are driven by drivers, etc..).

The problem is not in the drivers, but in the shape keys.
The character uses hundreds of corrective shape keys that are controlled by drivers.
When the addon disables drivers and shape keys, it leaves the shape keys **that were controlled by these drivers** enabled if their values are greater than 0.

I understand that the addon leaves them enabled because there is a check like "if shape key is not 0, then shape key is enabled". An additional check of the type "if the shape key is **controlled by the driver**, then the shape key will be disabled if there are checkboxes opposite the driver and shape keys" is needed.

If we disable the drivers of the corrective shape keys, then it is more correct to turn off the **corrective shape keys themselves** as well, so we will get a higher fps in the viewport. Because hundreds of shape keys reduce fps, even if they are not animated in any way.

**Comment by Mustard2** [comment]
Sure, this is exactly what I was trying to explain, and what I just added to #3 .

If you want you can check that version, where you should be able to choose if you want to disable shape keys with drivers or not.

**Comment by Mustard2** [comment]
This is scheduled to be closed with #3. If you try the version and you find any issue, or if after the merge request is closed the bug is still there, please feel free to re-open the issue if it is already closed.

**Comment by Art4DD** [comment]
Thank you so much for your work.
The new functions work out correctly.
Now there is no difference in fps between Diffeomorphic "Disable Drivers" and your addon, your addon is even better because it disables drivers and shape keys on all objects of the scene, and not separately selected.

Finally I can use Fast Normals, I couldn't because of different UV. Thank you.

**Comment by Mustard2** [comment]
You're welcome :)
