### ISSUE TITLE
Collection exceptions

### ISSUE THREAD

**Issue by ElectronicFilms** [Mustard2/MustardSimplify#5]
Hi, this is not really an issue, but is it possible for you to select a full collection as an exception instead of single objects? I don't know if it's even possible, but I thought I'd suggest...

-McLoek

**Comment by Mustard2** [comment]
Hi!

I think it might be possible, I'll see what I can do. :)

**Comment by Mustard2** [comment]
Added to #6. If you want to test the feature, let me know if it works. :)

This is scheduled to be closed as soon as the merge request is closed. Feel free to re-open the issue if the feature has some issues/you might want additional features about the same request. For new features of bug reports, please open a new Issue.

**Comment by ElectronicFilms** [comment]
I just tested it, and it workes perfectly! Thank you very much!
